version: 2
jobs:
  build-test-linux:
    docker:
      - image: circleci/golang:1.9.6
    steps:
      - checkout
      - run:
          name: Install deps
          command: sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev cmake libpcre3-dev libgmp-dev
      - run: mkdir build && cd build && cmake ..
      - run: cd build && make
      - run: cd build && make test
      - run:
          name: Copy Artifacts
          command: |
              mkdir -p /tmp/artifacts
              cp build/libsdk.a /tmp/artifacts/linux-gcc-64bit-libldapi.a
              cp build libsdkdynamic.so /tmp/artifacts/linux-gcc-64bit-libldapi.so
      - store_artifacts:
          path: /tmp/artifacts

  build-test-osx:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Install deps
          command: brew install cmake pcre gmp
      - run: mkdir build && cd build && cmake ..
      - run: cd build && make
      - run: cd build && make test
      - run:
          name: Copy Artifacts
          command: |
              mkdir -p /tmp/artifacts
              cp build/libsdk.a /tmp/artifacts/osx-clang-64bit-libldapi.a
              cp build/libsdkdynamic.so /tmp/artifacts/osx-clang-64bit-libldapi.so
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  build_and_test_all:
    jobs:
      - build-test-linux
      - build-test-osx
